version: "3.8"

services:
  webapp:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: webapp
    restart: always
    env_file: .env
    networks:
      - webapp
    ports:
      - 5000:5000

  mongodb:
    image: mongo:6.0.13-jammy
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - webapp
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
  

networks:
  webapp:
  