FROM python:3.10-bullseye

WORKDIR /home/master/discord

ENV TOKEN=ODg4MzczNjAyNzQxODAwOTcy.YURwZA.k-soevsEX6zfCH8hlm5Unak_gjM

COPY . .

RUN pip3 install --no-cache-dir --upgrade pip && pip3 install -r requirements.txt

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

CMD ["python", "WebScrap_GokuBlack.py"]
