name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: yuvals41
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: Application/webapp
        push: true
        load: false
        # tags: yuvals41/discordbot:${{ github.run_number }}
        tags: yuvals41/webapp:v1
        cache-from: |
          type=s3,region=eu-west-1,bucket=docker-cache-dammi,access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }},secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        cache-to: |
          type=s3,region=eu-west-1,bucket=docker-cache-dammi,access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }},secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Run Unit Tests in Docker Container
    #   continue-on-error: true
    #   run: docker run --rm yuvals41/admin:${{ github.run_number }}
